### PR TITLE
Fix/cus 151 - Azure -  error messages fix, cleanup, refactoring

### PR DESCRIPTION
**Pull request by plyubich**
# Description

This pull request is aimed to clean up the Error Handling for previous work on CUS-151. It contains no structural changes, however, it does contain some refactoring and clean up, hence a separate PR.

This PR also address some bug fixes related to:
- resourceApplication - no reference to this and file produces [] results
- missing Target Type RedisCache was not being uploaded to s3

image
image

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Validated in SaaSDev

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] My commit message/PR follows the contribution guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

### CODE REVIEW

**Review by plyubich — COMMENTED** [review]
@santhosh-challa please review. I checked the logs and data and it matches the previous collections + we are getting rediscache that was missed.

**Review by mkinchin-paladin — DISMISSED** [review]

**Comment by mkinchin-paladin** [comment]
it's huge, let's monitor Azure collector when it goes to prod

**Comment by plyubich** [comment]
@santhosh-challa please approve and merge. Output of files in saasdev match older archives. See screenshots.

**Review by santhosh-challa — APPROVED** [review]
LGTM

**Pull request merged**
