### PR TITLE
fix:[CUS-286] Fix dips is collected snapshot assets for vertex

### PR DESCRIPTION
**Pull request by ershad-paladin**
## Description

- issue: the issue is in the way we collect and describe snapshots in the collector. The collector seems to skip collecting if its not able to find and describe a snapshot id that it had listed
- in this case, the snapshot could not be found using snapshotID
- fix: handle exception during describing individual snapshots, so that it doesn't stop describing other listed snapshots
- handled the case when snapshot could not be found using snapshotID

### Problem
collector skips collecting snapshot if there is an issue describing a single snapshot

### Solution
handle exception for individual snapshots

## Type of change

**Please delete options that are not relevant.**

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Replicate the issue by hardcoding an invalid snapshotID
- [ ] Verify the other snapshots are collected

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ershad-paladin** [comment]
Actual issue in collector loaderror
image

Collector exception:
image

**Review by santhosh-challa — APPROVED** [review]
LGTM

**Comment by santhosh-challa** [comment]
@ershad-paladin please raise this to v1.8.0

**Comment by ershad-paladin** [comment]
> @ershad-paladin please raise this to v1.8.0

@santhosh-challa raised PR to v1.8.0 https://github.com/PaladinCloud/CE/pull/2163

**Pull request merged**
