### PR TITLE
Fix: Rename IssueID to ViolationID

### LINKED ISSUE #888: rename Issue ID column to Violation ID
The Violations List View needs to have the Issue ID column renamed to Violation ID

### PR DESCRIPTION
**Pull request by MarkovianPD**
# Description

Renames IssueID to ViolationID within Violations List View

Fixes #888 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

No testing performed.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] My commit message/PR follows the contribution guidelines of this project
- [X] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have added tests that prove my fix is effective or that my feature works
- [N/A] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki
N/A

### CODE REVIEW

**Comment by PaladinCloudJohn** [comment]
@MarkovianPD, thanks for taking a look at this! 

This is the right idea, but this might be the wrong place. Below is a screenshot showing the label that needs to be changed. From that, I expect a value to change from Issue ID to Violation ID. That's not clear in the original request, so apologies for that.
Screenshot 2023-02-28 at 4 47 13 PM

**Comment by MarkovianPD** [comment]
@PaladinCloudJohn Thank you for catching that! I believe I've made the changes in the correct location now.

**Review by PaladinCloudJohn — APPROVED** [review]
Nice, this looks good to me 👍

**Comment by MarkovianPD** [comment]
> Nice, this looks good to me 👍

Awesome!

**Pull request closed without merging**
