### PR TITLE
chore:[devops-242]Notifiy reviewer check for delete statement

### PR DESCRIPTION
**Pull request by rnithinpaladin**
## Description

Notify Reviewer that this Pr has delete statement In SQL files

## Type of change

Please delete options that are not relevant.

[ ] Bug fix (non-breaking change which fixes an issue)
[ ] New feature (non-breaking change which adds functionality)
[ ] Chore (no code changes)
[ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Yes,
https://github.com/PaladinCloud/CE/pull/2088
please review above Pr
Screenshot from 2024-02-05 18-16-05

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
[ ] Test B

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
I have added tests that prove my fix is effective or that my feature works
[ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by plyubich** [comment]
@rnithinpaladin does this also block the merge?

**Comment by rnithinpaladin** [comment]
> @rnithinpaladin does this also block the merge?
@plyubich 
No, 
Blocking needs to be done at the branch protection level.

**Comment by rnithinpaladin** [comment]
> @rnithinpaladin does this also block the merge?

@plyubich I did not find any workflow to block PR merges.

**Review by mkinchin-paladin — APPROVED** [review]
LGTM

**Review by santhosh-challa — APPROVED** [review]

**Pull request merged**
