### PR TITLE
Fix: Rename the columns

### LINKED ISSUE #970: [BUG] Admin: Policy: Change "Title" to "Policy" and "Asset" to "Asset Type"
In the admin section on the policy page, the first column needs to be changed from "Title" to "Policy".
We should update column two from "Asset" to "Asset Type" on that same page, as the listing is not individual assets.

### PR DESCRIPTION
**Pull request by arifa11111**
# Description

Rename the columns Title to Policy, Asset to Asset Type, and Cloud to Cloud Type.

Fixes #970 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Chore (no code changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] My commit message/PR follows the contribution guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other Information**:

List any documentation updates that are needed for the Wiki
#### Before Modification
Screenshot from 2023-03-20 18-39-13
Screenshot from 2023-03-20 18-39-32
Screenshot from 2023-03-21 17-21-43

#### After Modification
Screenshot from 2023-03-20 18-39-49

Screenshot from 2023-03-20 19-23-1
3

Screenshot from 2023-03-21 17-22-11

### CODE REVIEW

**Comment by PaladinCloudJohn** [comment]
@arifa11111 Thanks for this PR.  

It looks good, but since this change also updates the Policy Compliance Overview section on the Dashboard page, can you change that "Title" column to display "Policy"?

**Comment by arifa11111** [comment]
> @arifa11111 Thanks for this PR.
> 
> It looks good, but since this change also updates the Policy Compliance Overview section on the Dashboard page, can you change that "Title" column to display "Policy"?

Sure @PaladinCloudJohn

**Review by PaladinCloudJohn — APPROVED** [review]
Thanks @arifa11111 for making the change to the second title column

Reviewed the code and the PR looks good to me.

**Review by ranadheer-b — APPROVED** [review]
Looks good to me

**Review by santhosh-challa — APPROVED** [review]

**Pull request merged**
