### PR TITLE
Issue#969 Changed column name from Title to Policy

### PR DESCRIPTION
**Pull request by surajdubey08**
Changed column header value from "Title" in webapp\src\app\pacman-features\modules\compliance\policy-knowledgebase\policy-knowledgebase.component.ts to "Policy"

### CODE REVIEW

**Comment by PaladinCloudJohn** [comment]
This is a fix for #969

**Review by PaladinCloudJohn — APPROVED** [review]
This change looks good to me

**Review by plyubich — APPROVED** [review]

**Comment by plyubich** [comment]
@santhosh-challa @dheerajkholia-paladin @ranadheer-b can we get this merged please

**Comment by plyubich** [comment]
@santhosh-challa @dheerajkholia-paladin @ranadheer-b can we please get this merged

**Review by ranadheer-b — APPROVED** [review]

**Review by santhosh-challa — APPROVED** [review]

**Pull request merged**
