### PR TITLE
fix:[CORE-1647] Update K8s target types to their standardized name

### PR DESCRIPTION
**Pull request by ershad-paladin**
# Description

Updated the targetNames for k8s in gcp and azure in related policy rule classes and tables. For aws targetName is already correct as mentioned in the ticket.
https://paladincloud.atlassian.net/browse/CORE-1647?atlOrigin=eyJpIjoiMjllY2ZmNmQxZDEwNDNhNjkwMDcyOTY2NWRhMzFmODUiLCJwIjoiaiJ9

Fixes # (issue)
Fixes targetNames for k8s

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also
list any relevant details for your test configuration

- [x] Firstly, check the asset list displayed in asset page for asset group Azure/GCP. We should see the old asset type kubernetes/GKE cluster
- [x] Update the target types in tables. Run the azure and gcp collector. In local, since Im not able to run the gcp collector, I ran only the azure collector.
- [x] The data file with new targetName azure-aks.data will be generated. For gcp collector changes, we need to update on the CQ plugin side. As a workaround for gcp, I created a gcp-gke.data file in s3 with same content as in the old data file gcp-gkecluster.data
- [x] Run the shipper for gcp and azure.
- [x] Verify that new indices are created for targetNames azure_aks and gcp_gke in ES. Also verify the assets in those indices.
- [x] Goto the asset list page and verify the assets with new targetNames are displayed
- [x] Change the asset group and verify the assets with new targetNames are displayed similarly to the old targetNames
- [x] Run the policy rules for the assets aks and gke and verify the violations are displayed on Violation page

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] My commit message/PR follows the contribution guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# **Other information**:

List any documentation updates that are needed for the Wiki

### CODE REVIEW

**Review by mkinchin-paladin — CHANGES_REQUESTED** [review]
@ershad-paladin I need some more info from you on this PR.
1. Please fix the name of PR so it will contain whole task ID - it required for better automatization and task tracking.
2. how do you plan to test these changes? because they look like breaking changes and must be tested before it goes ii master.
3. Our mapper would still produce old names and we basically will lost the data. How do we plan to do avoid that? or at least minimize. I would try at least to push it close to each other and make sure that changes for both parts will be released during the same release.
4. I assume that there are some customers which have created asset groups using k8s indexes. How we gonna approach it?
5. Also we already have some data in OSearch for those GKE and AKS. Will that data be updated automatically or we need to write a script to make it happen?
6. And last - I assume EKS already has a proper name, right?

**Comment by ershad-paladin** [comment]
@mkinchin-paladin PFB my comments for the blow
> 1. Please fix the name of PR so it will contain whole task ID - it required for better automatization and task tracking.
_- done_
> 2. how do you plan to test these changes? because they look like breaking changes and must be tested before it goes ii master.
_- I have just added the steps on how I tested these changes in the description_
> 3. Our mapper would still produce old names and we basically will lost the data. How do we plan to do avoid that? or at least minimize. I would try at least to push it close to each other and make sure that changes for both parts will be released during the same release.
_- I have added a commit for the azure collector change. For gcp, we need change on the CQ plugin side_
> 4. I assume that there are some customers which have created asset groups using k8s indexes. How we gonna approach it?
_- We are adding the same aliases to the new indices also. So, the assets on the new indices will be displayed just like before_
> 5. Also we already have some data in OSearch for those GKE and AKS. Will that data be updated automatically or we need to write a script to make it happen?
_- I have attached migration scripts to the jira ticket. We have to run them once the new indices are created_
> 6. And last - I assume EKS already has a proper name, right?
_- Yes. we don't need any change for EKS._

Also PFB my proposed steps for the complete migration. Please let me know if this needs any changes:

- update the new targetNames for k8s in cf_target and other tables
- creating a dummy shipper job(just for the sake of creating the new index with aliases)
- delete all the documents in the new index which are created by the dummy shipper job
- run the attached ES query which will migrate all the data from old index to the new index
- verify new index data and test the application UI
- delete the old index

**Comment by ershad-paladin** [comment]
Before fix:
image
image

After fix:
image
image

**Review by plyubich — DISMISSED** [review]
LGTM

**Comment by mkinchin-paladin** [comment]
@ershad-paladin 
1. I was talking about title of the PR, it should be [CORE-1647], not just [1647], this was Jira will pick up this PR and add it to the ticket. Minor, but better to make it a habit :)
3. Please do it as well, it's in data-mapper project, you would need to make some changes in mapping files, coordinate with @arunpaladin @akashpaladin or @AnandPaladin on that - they should help.

**Comment by mkinchin-paladin** [comment]
> @mkinchin-paladin PFB my comments inline for the blow qns:
> 
> > 1. Please fix the name of PR so it will contain whole task ID - it required for better automatization and task tracking.
> >    _- done_
> > 2. how do you plan to test these changes? because they look like breaking changes and must be tested before it goes ii master.
> >    _- I have just added the steps on how I tested these changes in the description_
> > 3. Our mapper would still produce old names and we basically will lost the data. How do we plan to do avoid that? or at least minimize. I would try at least to push it close to each other and make sure that changes for both parts will be released during the same release.
> >    _- I have added a commit for the azure collector change. For gcp, we need change on the CQ plugin side_
> > 4. I assume that there are some customers which have created asset groups using k8s indexes. How we gonna approach it?
> >    _- We are adding the same aliases to the new indices also. So, the assets on the new indices will be displayed just like before_
> > 5. Also we already have some data in OSearch for those GKE and AKS. Will that data be updated automatically or we need to write a script to make it happen?
> >    _- I have attached migration scripts to the jira ticket. We have to run them once the new indices are created_
> > 6. And last - I assume EKS already has a proper name, right?
> >    _- Yes. we don't need any change for EKS._
> 
> Also PFB my proposed steps for the complete migration. Please let me know if this needs any changes:
> 
> * update the new targetNames for k8s in cf_target and other tables
> * creating a dummy shipper job(just for the sake of creating the new index with aliases)
> * delete all the documents in the new index which are created by the dummy shipper job
> * run the attached ES query which will migrate all the data from old index to the new index
> * verify new index data and test the application UI
> * delete the old index

Sounds good. Will approve as soon as we have mapper changes ready to be pushed as well.

**Comment by ershad-paladin** [comment]
> @ershad-paladin
> 
> 1. I was talking about title of the PR, it should be [CORE-1647](https://paladincloud.atlassian.net/browse/CORE-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ), not just [1647], this was Jira will pick up this PR and add it to the ticket. Minor, but better to make it a habit :)
> 2. Please do it as well, it's in data-mapper project, you would need to make some changes in mapping files, coordinate with @arunpaladin @akashpaladin or @AnandPaladin on that - they should help.

1. sorry, missed it and updated now
2. created the PR for data-mapper with the help of @akashpaladin, PR: https://github.com/PaladinCloud/Plugins/pull/89

**Review by santhosh-challa — APPROVED** [review]
LGTM

**Comment by santhosh-challa** [comment]
@mkinchin-paladin I think this can be merged. Let me know if anything is needed. Merging this.

**Pull request merged**
